### ISSUE TITLE
plhudnew checklist

### ISSUE THREAD

**Issue by yugecin** [yugecin/scmcleoscripts#4]
* [x] the actual hud with esp, name & distance
* [x] minimize artifacts
* [x] check for [redacted]
* [x] opacity
* [x] put airportcount & sprintf in runonce asm
* [x] radar
* [x] do not loop when viewdistance is 0
* [x] smart mode radius should be bigger
* [x] find a different place to hook so it still shows when the hud is hidden (sa-mp)
* [x] fix text being wrapped when other text is on screen
* [x] branding
* [x] make sure the menu is visible/usable on screen for low res
* [x] change font size for the actual hud
* [ ] ~~(make font size configurable)~~
* [x] (make color configurable)
* [ ] ~~(configurable opacity)~~
